/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.fdk.service;
@org.apache.avro.specific.AvroGenerated
public enum ServiceEventType implements org.apache.avro.generic.GenericEnumSymbol<ServiceEventType> {
  SERVICE_HARVESTED, SERVICE_REASONED, SERVICE_REMOVED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ServiceEventType\",\"namespace\":\"no.fdk.service\",\"symbols\":[\"SERVICE_HARVESTED\",\"SERVICE_REASONED\",\"SERVICE_REMOVED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
