/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.fdk.harvest;
@org.apache.avro.specific.AvroGenerated
public enum HarvestPhase implements org.apache.avro.generic.GenericEnumSymbol<HarvestPhase> {
  INITIATING, HARVESTING, REASONING, RDF_PARSING, RESOURCE_PROCESSING, SEARCH_PROCESSING, AI_SEARCH_PROCESSING, SPARQL_PROCESSING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"HarvestPhase\",\"namespace\":\"no.fdk.harvest\",\"symbols\":[\"INITIATING\",\"HARVESTING\",\"REASONING\",\"RDF_PARSING\",\"RESOURCE_PROCESSING\",\"SEARCH_PROCESSING\",\"AI_SEARCH_PROCESSING\",\"SPARQL_PROCESSING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
