/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.fdk.harvest;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class HarvestEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5248602439508991857L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HarvestEvent\",\"namespace\":\"no.fdk.harvest\",\"fields\":[{\"name\":\"phase\",\"type\":{\"type\":\"enum\",\"name\":\"HarvestPhase\",\"symbols\":[\"INITIATING\",\"HARVESTING\",\"REASONING\",\"RDF_PARSING\",\"RESOURCE_PROCESSING\",\"SEARCH_PROCESSING\",\"AI_SEARCH_PROCESSING\",\"SPARQL_PROCESSING\"]}},{\"name\":\"runId\",\"type\":[\"null\",\"string\"],\"doc\":\"Unique identifier (UUID) for the harvest run this event belongs to\",\"default\":null},{\"name\":\"dataType\",\"type\":{\"type\":\"enum\",\"name\":\"DataType\",\"symbols\":[\"concept\",\"dataset\",\"informationmodel\",\"dataservice\",\"publicService\",\"event\"]}},{\"name\":\"dataSourceId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"dataSourceUrl\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"acceptHeader\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"fdkId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"resourceUri\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"startTime\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"endTime\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"errorMessage\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"changedResourcesCount\",\"type\":[\"null\",\"int\"],\"doc\":\"Number of changed resources (only for DATASOURCE_RESOURCE_EXTRACTION)\",\"default\":null},{\"name\":\"unchangedResourcesCount\",\"type\":[\"null\",\"int\"],\"doc\":\"Number of unchanged resources (only for DATASOURCE_RESOURCE_EXTRACTION)\",\"default\":null},{\"name\":\"removedResourcesCount\",\"type\":[\"null\",\"int\"],\"doc\":\"Number of removed resources (only for DATASOURCE_RESOURCE_EXTRACTION)\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<HarvestEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<HarvestEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<HarvestEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<HarvestEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<HarvestEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this HarvestEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a HarvestEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a HarvestEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static HarvestEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private no.fdk.harvest.HarvestPhase phase;
  /** Unique identifier (UUID) for the harvest run this event belongs to */
  private java.lang.CharSequence runId;
  private no.fdk.harvest.DataType dataType;
  private java.lang.CharSequence dataSourceId;
  private java.lang.CharSequence dataSourceUrl;
  private java.lang.CharSequence acceptHeader;
  private java.lang.CharSequence fdkId;
  private java.lang.CharSequence resourceUri;
  private java.lang.CharSequence startTime;
  private java.lang.CharSequence endTime;
  private java.lang.CharSequence errorMessage;
  /** Number of changed resources (only for DATASOURCE_RESOURCE_EXTRACTION) */
  private java.lang.Integer changedResourcesCount;
  /** Number of unchanged resources (only for DATASOURCE_RESOURCE_EXTRACTION) */
  private java.lang.Integer unchangedResourcesCount;
  /** Number of removed resources (only for DATASOURCE_RESOURCE_EXTRACTION) */
  private java.lang.Integer removedResourcesCount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HarvestEvent() {}

  /**
   * All-args constructor.
   * @param phase The new value for phase
   * @param runId Unique identifier (UUID) for the harvest run this event belongs to
   * @param dataType The new value for dataType
   * @param dataSourceId The new value for dataSourceId
   * @param dataSourceUrl The new value for dataSourceUrl
   * @param acceptHeader The new value for acceptHeader
   * @param fdkId The new value for fdkId
   * @param resourceUri The new value for resourceUri
   * @param startTime The new value for startTime
   * @param endTime The new value for endTime
   * @param errorMessage The new value for errorMessage
   * @param changedResourcesCount Number of changed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
   * @param unchangedResourcesCount Number of unchanged resources (only for DATASOURCE_RESOURCE_EXTRACTION)
   * @param removedResourcesCount Number of removed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
   */
  public HarvestEvent(no.fdk.harvest.HarvestPhase phase, java.lang.CharSequence runId, no.fdk.harvest.DataType dataType, java.lang.CharSequence dataSourceId, java.lang.CharSequence dataSourceUrl, java.lang.CharSequence acceptHeader, java.lang.CharSequence fdkId, java.lang.CharSequence resourceUri, java.lang.CharSequence startTime, java.lang.CharSequence endTime, java.lang.CharSequence errorMessage, java.lang.Integer changedResourcesCount, java.lang.Integer unchangedResourcesCount, java.lang.Integer removedResourcesCount) {
    this.phase = phase;
    this.runId = runId;
    this.dataType = dataType;
    this.dataSourceId = dataSourceId;
    this.dataSourceUrl = dataSourceUrl;
    this.acceptHeader = acceptHeader;
    this.fdkId = fdkId;
    this.resourceUri = resourceUri;
    this.startTime = startTime;
    this.endTime = endTime;
    this.errorMessage = errorMessage;
    this.changedResourcesCount = changedResourcesCount;
    this.unchangedResourcesCount = unchangedResourcesCount;
    this.removedResourcesCount = removedResourcesCount;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return phase;
    case 1: return runId;
    case 2: return dataType;
    case 3: return dataSourceId;
    case 4: return dataSourceUrl;
    case 5: return acceptHeader;
    case 6: return fdkId;
    case 7: return resourceUri;
    case 8: return startTime;
    case 9: return endTime;
    case 10: return errorMessage;
    case 11: return changedResourcesCount;
    case 12: return unchangedResourcesCount;
    case 13: return removedResourcesCount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: phase = (no.fdk.harvest.HarvestPhase)value$; break;
    case 1: runId = (java.lang.CharSequence)value$; break;
    case 2: dataType = (no.fdk.harvest.DataType)value$; break;
    case 3: dataSourceId = (java.lang.CharSequence)value$; break;
    case 4: dataSourceUrl = (java.lang.CharSequence)value$; break;
    case 5: acceptHeader = (java.lang.CharSequence)value$; break;
    case 6: fdkId = (java.lang.CharSequence)value$; break;
    case 7: resourceUri = (java.lang.CharSequence)value$; break;
    case 8: startTime = (java.lang.CharSequence)value$; break;
    case 9: endTime = (java.lang.CharSequence)value$; break;
    case 10: errorMessage = (java.lang.CharSequence)value$; break;
    case 11: changedResourcesCount = (java.lang.Integer)value$; break;
    case 12: unchangedResourcesCount = (java.lang.Integer)value$; break;
    case 13: removedResourcesCount = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'phase' field.
   * @return The value of the 'phase' field.
   */
  public no.fdk.harvest.HarvestPhase getPhase() {
    return phase;
  }


  /**
   * Sets the value of the 'phase' field.
   * @param value the value to set.
   */
  public void setPhase(no.fdk.harvest.HarvestPhase value) {
    this.phase = value;
  }

  /**
   * Gets the value of the 'runId' field.
   * @return Unique identifier (UUID) for the harvest run this event belongs to
   */
  public java.lang.CharSequence getRunId() {
    return runId;
  }


  /**
   * Sets the value of the 'runId' field.
   * Unique identifier (UUID) for the harvest run this event belongs to
   * @param value the value to set.
   */
  public void setRunId(java.lang.CharSequence value) {
    this.runId = value;
  }

  /**
   * Gets the value of the 'dataType' field.
   * @return The value of the 'dataType' field.
   */
  public no.fdk.harvest.DataType getDataType() {
    return dataType;
  }


  /**
   * Sets the value of the 'dataType' field.
   * @param value the value to set.
   */
  public void setDataType(no.fdk.harvest.DataType value) {
    this.dataType = value;
  }

  /**
   * Gets the value of the 'dataSourceId' field.
   * @return The value of the 'dataSourceId' field.
   */
  public java.lang.CharSequence getDataSourceId() {
    return dataSourceId;
  }


  /**
   * Sets the value of the 'dataSourceId' field.
   * @param value the value to set.
   */
  public void setDataSourceId(java.lang.CharSequence value) {
    this.dataSourceId = value;
  }

  /**
   * Gets the value of the 'dataSourceUrl' field.
   * @return The value of the 'dataSourceUrl' field.
   */
  public java.lang.CharSequence getDataSourceUrl() {
    return dataSourceUrl;
  }


  /**
   * Sets the value of the 'dataSourceUrl' field.
   * @param value the value to set.
   */
  public void setDataSourceUrl(java.lang.CharSequence value) {
    this.dataSourceUrl = value;
  }

  /**
   * Gets the value of the 'acceptHeader' field.
   * @return The value of the 'acceptHeader' field.
   */
  public java.lang.CharSequence getAcceptHeader() {
    return acceptHeader;
  }


  /**
   * Sets the value of the 'acceptHeader' field.
   * @param value the value to set.
   */
  public void setAcceptHeader(java.lang.CharSequence value) {
    this.acceptHeader = value;
  }

  /**
   * Gets the value of the 'fdkId' field.
   * @return The value of the 'fdkId' field.
   */
  public java.lang.CharSequence getFdkId() {
    return fdkId;
  }


  /**
   * Sets the value of the 'fdkId' field.
   * @param value the value to set.
   */
  public void setFdkId(java.lang.CharSequence value) {
    this.fdkId = value;
  }

  /**
   * Gets the value of the 'resourceUri' field.
   * @return The value of the 'resourceUri' field.
   */
  public java.lang.CharSequence getResourceUri() {
    return resourceUri;
  }


  /**
   * Sets the value of the 'resourceUri' field.
   * @param value the value to set.
   */
  public void setResourceUri(java.lang.CharSequence value) {
    this.resourceUri = value;
  }

  /**
   * Gets the value of the 'startTime' field.
   * @return The value of the 'startTime' field.
   */
  public java.lang.CharSequence getStartTime() {
    return startTime;
  }


  /**
   * Sets the value of the 'startTime' field.
   * @param value the value to set.
   */
  public void setStartTime(java.lang.CharSequence value) {
    this.startTime = value;
  }

  /**
   * Gets the value of the 'endTime' field.
   * @return The value of the 'endTime' field.
   */
  public java.lang.CharSequence getEndTime() {
    return endTime;
  }


  /**
   * Sets the value of the 'endTime' field.
   * @param value the value to set.
   */
  public void setEndTime(java.lang.CharSequence value) {
    this.endTime = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   * @return The value of the 'errorMessage' field.
   */
  public java.lang.CharSequence getErrorMessage() {
    return errorMessage;
  }


  /**
   * Sets the value of the 'errorMessage' field.
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.CharSequence value) {
    this.errorMessage = value;
  }

  /**
   * Gets the value of the 'changedResourcesCount' field.
   * @return Number of changed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
   */
  public java.lang.Integer getChangedResourcesCount() {
    return changedResourcesCount;
  }


  /**
   * Sets the value of the 'changedResourcesCount' field.
   * Number of changed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
   * @param value the value to set.
   */
  public void setChangedResourcesCount(java.lang.Integer value) {
    this.changedResourcesCount = value;
  }

  /**
   * Gets the value of the 'unchangedResourcesCount' field.
   * @return Number of unchanged resources (only for DATASOURCE_RESOURCE_EXTRACTION)
   */
  public java.lang.Integer getUnchangedResourcesCount() {
    return unchangedResourcesCount;
  }


  /**
   * Sets the value of the 'unchangedResourcesCount' field.
   * Number of unchanged resources (only for DATASOURCE_RESOURCE_EXTRACTION)
   * @param value the value to set.
   */
  public void setUnchangedResourcesCount(java.lang.Integer value) {
    this.unchangedResourcesCount = value;
  }

  /**
   * Gets the value of the 'removedResourcesCount' field.
   * @return Number of removed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
   */
  public java.lang.Integer getRemovedResourcesCount() {
    return removedResourcesCount;
  }


  /**
   * Sets the value of the 'removedResourcesCount' field.
   * Number of removed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
   * @param value the value to set.
   */
  public void setRemovedResourcesCount(java.lang.Integer value) {
    this.removedResourcesCount = value;
  }

  /**
   * Creates a new HarvestEvent RecordBuilder.
   * @return A new HarvestEvent RecordBuilder
   */
  public static no.fdk.harvest.HarvestEvent.Builder newBuilder() {
    return new no.fdk.harvest.HarvestEvent.Builder();
  }

  /**
   * Creates a new HarvestEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new HarvestEvent RecordBuilder
   */
  public static no.fdk.harvest.HarvestEvent.Builder newBuilder(no.fdk.harvest.HarvestEvent.Builder other) {
    if (other == null) {
      return new no.fdk.harvest.HarvestEvent.Builder();
    } else {
      return new no.fdk.harvest.HarvestEvent.Builder(other);
    }
  }

  /**
   * Creates a new HarvestEvent RecordBuilder by copying an existing HarvestEvent instance.
   * @param other The existing instance to copy.
   * @return A new HarvestEvent RecordBuilder
   */
  public static no.fdk.harvest.HarvestEvent.Builder newBuilder(no.fdk.harvest.HarvestEvent other) {
    if (other == null) {
      return new no.fdk.harvest.HarvestEvent.Builder();
    } else {
      return new no.fdk.harvest.HarvestEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for HarvestEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HarvestEvent>
    implements org.apache.avro.data.RecordBuilder<HarvestEvent> {

    private no.fdk.harvest.HarvestPhase phase;
    /** Unique identifier (UUID) for the harvest run this event belongs to */
    private java.lang.CharSequence runId;
    private no.fdk.harvest.DataType dataType;
    private java.lang.CharSequence dataSourceId;
    private java.lang.CharSequence dataSourceUrl;
    private java.lang.CharSequence acceptHeader;
    private java.lang.CharSequence fdkId;
    private java.lang.CharSequence resourceUri;
    private java.lang.CharSequence startTime;
    private java.lang.CharSequence endTime;
    private java.lang.CharSequence errorMessage;
    /** Number of changed resources (only for DATASOURCE_RESOURCE_EXTRACTION) */
    private java.lang.Integer changedResourcesCount;
    /** Number of unchanged resources (only for DATASOURCE_RESOURCE_EXTRACTION) */
    private java.lang.Integer unchangedResourcesCount;
    /** Number of removed resources (only for DATASOURCE_RESOURCE_EXTRACTION) */
    private java.lang.Integer removedResourcesCount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.fdk.harvest.HarvestEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.phase)) {
        this.phase = data().deepCopy(fields()[0].schema(), other.phase);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.runId)) {
        this.runId = data().deepCopy(fields()[1].schema(), other.runId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.dataType)) {
        this.dataType = data().deepCopy(fields()[2].schema(), other.dataType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.dataSourceId)) {
        this.dataSourceId = data().deepCopy(fields()[3].schema(), other.dataSourceId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.dataSourceUrl)) {
        this.dataSourceUrl = data().deepCopy(fields()[4].schema(), other.dataSourceUrl);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.acceptHeader)) {
        this.acceptHeader = data().deepCopy(fields()[5].schema(), other.acceptHeader);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.fdkId)) {
        this.fdkId = data().deepCopy(fields()[6].schema(), other.fdkId);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.resourceUri)) {
        this.resourceUri = data().deepCopy(fields()[7].schema(), other.resourceUri);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.startTime)) {
        this.startTime = data().deepCopy(fields()[8].schema(), other.startTime);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.endTime)) {
        this.endTime = data().deepCopy(fields()[9].schema(), other.endTime);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[10].schema(), other.errorMessage);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.changedResourcesCount)) {
        this.changedResourcesCount = data().deepCopy(fields()[11].schema(), other.changedResourcesCount);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.unchangedResourcesCount)) {
        this.unchangedResourcesCount = data().deepCopy(fields()[12].schema(), other.unchangedResourcesCount);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.removedResourcesCount)) {
        this.removedResourcesCount = data().deepCopy(fields()[13].schema(), other.removedResourcesCount);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing HarvestEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(no.fdk.harvest.HarvestEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.phase)) {
        this.phase = data().deepCopy(fields()[0].schema(), other.phase);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.runId)) {
        this.runId = data().deepCopy(fields()[1].schema(), other.runId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dataType)) {
        this.dataType = data().deepCopy(fields()[2].schema(), other.dataType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dataSourceId)) {
        this.dataSourceId = data().deepCopy(fields()[3].schema(), other.dataSourceId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.dataSourceUrl)) {
        this.dataSourceUrl = data().deepCopy(fields()[4].schema(), other.dataSourceUrl);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.acceptHeader)) {
        this.acceptHeader = data().deepCopy(fields()[5].schema(), other.acceptHeader);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.fdkId)) {
        this.fdkId = data().deepCopy(fields()[6].schema(), other.fdkId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.resourceUri)) {
        this.resourceUri = data().deepCopy(fields()[7].schema(), other.resourceUri);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.startTime)) {
        this.startTime = data().deepCopy(fields()[8].schema(), other.startTime);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.endTime)) {
        this.endTime = data().deepCopy(fields()[9].schema(), other.endTime);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[10].schema(), other.errorMessage);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.changedResourcesCount)) {
        this.changedResourcesCount = data().deepCopy(fields()[11].schema(), other.changedResourcesCount);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.unchangedResourcesCount)) {
        this.unchangedResourcesCount = data().deepCopy(fields()[12].schema(), other.unchangedResourcesCount);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.removedResourcesCount)) {
        this.removedResourcesCount = data().deepCopy(fields()[13].schema(), other.removedResourcesCount);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'phase' field.
      * @return The value.
      */
    public no.fdk.harvest.HarvestPhase getPhase() {
      return phase;
    }


    /**
      * Sets the value of the 'phase' field.
      * @param value The value of 'phase'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setPhase(no.fdk.harvest.HarvestPhase value) {
      validate(fields()[0], value);
      this.phase = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'phase' field has been set.
      * @return True if the 'phase' field has been set, false otherwise.
      */
    public boolean hasPhase() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'phase' field.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearPhase() {
      phase = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'runId' field.
      * Unique identifier (UUID) for the harvest run this event belongs to
      * @return The value.
      */
    public java.lang.CharSequence getRunId() {
      return runId;
    }


    /**
      * Sets the value of the 'runId' field.
      * Unique identifier (UUID) for the harvest run this event belongs to
      * @param value The value of 'runId'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setRunId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.runId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'runId' field has been set.
      * Unique identifier (UUID) for the harvest run this event belongs to
      * @return True if the 'runId' field has been set, false otherwise.
      */
    public boolean hasRunId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'runId' field.
      * Unique identifier (UUID) for the harvest run this event belongs to
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearRunId() {
      runId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'dataType' field.
      * @return The value.
      */
    public no.fdk.harvest.DataType getDataType() {
      return dataType;
    }


    /**
      * Sets the value of the 'dataType' field.
      * @param value The value of 'dataType'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setDataType(no.fdk.harvest.DataType value) {
      validate(fields()[2], value);
      this.dataType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'dataType' field has been set.
      * @return True if the 'dataType' field has been set, false otherwise.
      */
    public boolean hasDataType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'dataType' field.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearDataType() {
      dataType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'dataSourceId' field.
      * @return The value.
      */
    public java.lang.CharSequence getDataSourceId() {
      return dataSourceId;
    }


    /**
      * Sets the value of the 'dataSourceId' field.
      * @param value The value of 'dataSourceId'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setDataSourceId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.dataSourceId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'dataSourceId' field has been set.
      * @return True if the 'dataSourceId' field has been set, false otherwise.
      */
    public boolean hasDataSourceId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'dataSourceId' field.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearDataSourceId() {
      dataSourceId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'dataSourceUrl' field.
      * @return The value.
      */
    public java.lang.CharSequence getDataSourceUrl() {
      return dataSourceUrl;
    }


    /**
      * Sets the value of the 'dataSourceUrl' field.
      * @param value The value of 'dataSourceUrl'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setDataSourceUrl(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.dataSourceUrl = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'dataSourceUrl' field has been set.
      * @return True if the 'dataSourceUrl' field has been set, false otherwise.
      */
    public boolean hasDataSourceUrl() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'dataSourceUrl' field.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearDataSourceUrl() {
      dataSourceUrl = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'acceptHeader' field.
      * @return The value.
      */
    public java.lang.CharSequence getAcceptHeader() {
      return acceptHeader;
    }


    /**
      * Sets the value of the 'acceptHeader' field.
      * @param value The value of 'acceptHeader'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setAcceptHeader(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.acceptHeader = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'acceptHeader' field has been set.
      * @return True if the 'acceptHeader' field has been set, false otherwise.
      */
    public boolean hasAcceptHeader() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'acceptHeader' field.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearAcceptHeader() {
      acceptHeader = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'fdkId' field.
      * @return The value.
      */
    public java.lang.CharSequence getFdkId() {
      return fdkId;
    }


    /**
      * Sets the value of the 'fdkId' field.
      * @param value The value of 'fdkId'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setFdkId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.fdkId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'fdkId' field has been set.
      * @return True if the 'fdkId' field has been set, false otherwise.
      */
    public boolean hasFdkId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'fdkId' field.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearFdkId() {
      fdkId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'resourceUri' field.
      * @return The value.
      */
    public java.lang.CharSequence getResourceUri() {
      return resourceUri;
    }


    /**
      * Sets the value of the 'resourceUri' field.
      * @param value The value of 'resourceUri'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setResourceUri(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.resourceUri = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'resourceUri' field has been set.
      * @return True if the 'resourceUri' field has been set, false otherwise.
      */
    public boolean hasResourceUri() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'resourceUri' field.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearResourceUri() {
      resourceUri = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'startTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getStartTime() {
      return startTime;
    }


    /**
      * Sets the value of the 'startTime' field.
      * @param value The value of 'startTime'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setStartTime(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.startTime = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'startTime' field has been set.
      * @return True if the 'startTime' field has been set, false otherwise.
      */
    public boolean hasStartTime() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'startTime' field.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearStartTime() {
      startTime = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'endTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getEndTime() {
      return endTime;
    }


    /**
      * Sets the value of the 'endTime' field.
      * @param value The value of 'endTime'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setEndTime(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.endTime = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'endTime' field has been set.
      * @return True if the 'endTime' field has been set, false otherwise.
      */
    public boolean hasEndTime() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'endTime' field.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearEndTime() {
      endTime = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorMessage' field.
      * @return The value.
      */
    public java.lang.CharSequence getErrorMessage() {
      return errorMessage;
    }


    /**
      * Sets the value of the 'errorMessage' field.
      * @param value The value of 'errorMessage'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setErrorMessage(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.errorMessage = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'errorMessage' field has been set.
      * @return True if the 'errorMessage' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'errorMessage' field.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'changedResourcesCount' field.
      * Number of changed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @return The value.
      */
    public java.lang.Integer getChangedResourcesCount() {
      return changedResourcesCount;
    }


    /**
      * Sets the value of the 'changedResourcesCount' field.
      * Number of changed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @param value The value of 'changedResourcesCount'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setChangedResourcesCount(java.lang.Integer value) {
      validate(fields()[11], value);
      this.changedResourcesCount = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'changedResourcesCount' field has been set.
      * Number of changed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @return True if the 'changedResourcesCount' field has been set, false otherwise.
      */
    public boolean hasChangedResourcesCount() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'changedResourcesCount' field.
      * Number of changed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearChangedResourcesCount() {
      changedResourcesCount = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'unchangedResourcesCount' field.
      * Number of unchanged resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @return The value.
      */
    public java.lang.Integer getUnchangedResourcesCount() {
      return unchangedResourcesCount;
    }


    /**
      * Sets the value of the 'unchangedResourcesCount' field.
      * Number of unchanged resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @param value The value of 'unchangedResourcesCount'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setUnchangedResourcesCount(java.lang.Integer value) {
      validate(fields()[12], value);
      this.unchangedResourcesCount = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'unchangedResourcesCount' field has been set.
      * Number of unchanged resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @return True if the 'unchangedResourcesCount' field has been set, false otherwise.
      */
    public boolean hasUnchangedResourcesCount() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'unchangedResourcesCount' field.
      * Number of unchanged resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearUnchangedResourcesCount() {
      unchangedResourcesCount = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'removedResourcesCount' field.
      * Number of removed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @return The value.
      */
    public java.lang.Integer getRemovedResourcesCount() {
      return removedResourcesCount;
    }


    /**
      * Sets the value of the 'removedResourcesCount' field.
      * Number of removed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @param value The value of 'removedResourcesCount'.
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder setRemovedResourcesCount(java.lang.Integer value) {
      validate(fields()[13], value);
      this.removedResourcesCount = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'removedResourcesCount' field has been set.
      * Number of removed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @return True if the 'removedResourcesCount' field has been set, false otherwise.
      */
    public boolean hasRemovedResourcesCount() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'removedResourcesCount' field.
      * Number of removed resources (only for DATASOURCE_RESOURCE_EXTRACTION)
      * @return This builder.
      */
    public no.fdk.harvest.HarvestEvent.Builder clearRemovedResourcesCount() {
      removedResourcesCount = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public HarvestEvent build() {
      try {
        HarvestEvent record = new HarvestEvent();
        record.phase = fieldSetFlags()[0] ? this.phase : (no.fdk.harvest.HarvestPhase) defaultValue(fields()[0]);
        record.runId = fieldSetFlags()[1] ? this.runId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.dataType = fieldSetFlags()[2] ? this.dataType : (no.fdk.harvest.DataType) defaultValue(fields()[2]);
        record.dataSourceId = fieldSetFlags()[3] ? this.dataSourceId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.dataSourceUrl = fieldSetFlags()[4] ? this.dataSourceUrl : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.acceptHeader = fieldSetFlags()[5] ? this.acceptHeader : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.fdkId = fieldSetFlags()[6] ? this.fdkId : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.resourceUri = fieldSetFlags()[7] ? this.resourceUri : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.startTime = fieldSetFlags()[8] ? this.startTime : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.endTime = fieldSetFlags()[9] ? this.endTime : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.errorMessage = fieldSetFlags()[10] ? this.errorMessage : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.changedResourcesCount = fieldSetFlags()[11] ? this.changedResourcesCount : (java.lang.Integer) defaultValue(fields()[11]);
        record.unchangedResourcesCount = fieldSetFlags()[12] ? this.unchangedResourcesCount : (java.lang.Integer) defaultValue(fields()[12]);
        record.removedResourcesCount = fieldSetFlags()[13] ? this.removedResourcesCount : (java.lang.Integer) defaultValue(fields()[13]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<HarvestEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<HarvestEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<HarvestEvent>
    READER$ = (org.apache.avro.io.DatumReader<HarvestEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.phase.ordinal());

    if (this.runId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.runId);
    }

    out.writeEnum(this.dataType.ordinal());

    if (this.dataSourceId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.dataSourceId);
    }

    if (this.dataSourceUrl == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.dataSourceUrl);
    }

    if (this.acceptHeader == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.acceptHeader);
    }

    if (this.fdkId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.fdkId);
    }

    if (this.resourceUri == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.resourceUri);
    }

    if (this.startTime == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.startTime);
    }

    if (this.endTime == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.endTime);
    }

    if (this.errorMessage == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.errorMessage);
    }

    if (this.changedResourcesCount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.changedResourcesCount);
    }

    if (this.unchangedResourcesCount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.unchangedResourcesCount);
    }

    if (this.removedResourcesCount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.removedResourcesCount);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.phase = no.fdk.harvest.HarvestPhase.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.runId = null;
      } else {
        this.runId = in.readString(this.runId instanceof Utf8 ? (Utf8)this.runId : null);
      }

      this.dataType = no.fdk.harvest.DataType.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.dataSourceId = null;
      } else {
        this.dataSourceId = in.readString(this.dataSourceId instanceof Utf8 ? (Utf8)this.dataSourceId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.dataSourceUrl = null;
      } else {
        this.dataSourceUrl = in.readString(this.dataSourceUrl instanceof Utf8 ? (Utf8)this.dataSourceUrl : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.acceptHeader = null;
      } else {
        this.acceptHeader = in.readString(this.acceptHeader instanceof Utf8 ? (Utf8)this.acceptHeader : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.fdkId = null;
      } else {
        this.fdkId = in.readString(this.fdkId instanceof Utf8 ? (Utf8)this.fdkId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.resourceUri = null;
      } else {
        this.resourceUri = in.readString(this.resourceUri instanceof Utf8 ? (Utf8)this.resourceUri : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.startTime = null;
      } else {
        this.startTime = in.readString(this.startTime instanceof Utf8 ? (Utf8)this.startTime : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.endTime = null;
      } else {
        this.endTime = in.readString(this.endTime instanceof Utf8 ? (Utf8)this.endTime : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.errorMessage = null;
      } else {
        this.errorMessage = in.readString(this.errorMessage instanceof Utf8 ? (Utf8)this.errorMessage : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.changedResourcesCount = null;
      } else {
        this.changedResourcesCount = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.unchangedResourcesCount = null;
      } else {
        this.unchangedResourcesCount = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.removedResourcesCount = null;
      } else {
        this.removedResourcesCount = in.readInt();
      }

    } else {
      for (int i = 0; i < 14; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.phase = no.fdk.harvest.HarvestPhase.values()[in.readEnum()];
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.runId = null;
          } else {
            this.runId = in.readString(this.runId instanceof Utf8 ? (Utf8)this.runId : null);
          }
          break;

        case 2:
          this.dataType = no.fdk.harvest.DataType.values()[in.readEnum()];
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.dataSourceId = null;
          } else {
            this.dataSourceId = in.readString(this.dataSourceId instanceof Utf8 ? (Utf8)this.dataSourceId : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.dataSourceUrl = null;
          } else {
            this.dataSourceUrl = in.readString(this.dataSourceUrl instanceof Utf8 ? (Utf8)this.dataSourceUrl : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.acceptHeader = null;
          } else {
            this.acceptHeader = in.readString(this.acceptHeader instanceof Utf8 ? (Utf8)this.acceptHeader : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.fdkId = null;
          } else {
            this.fdkId = in.readString(this.fdkId instanceof Utf8 ? (Utf8)this.fdkId : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.resourceUri = null;
          } else {
            this.resourceUri = in.readString(this.resourceUri instanceof Utf8 ? (Utf8)this.resourceUri : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.startTime = null;
          } else {
            this.startTime = in.readString(this.startTime instanceof Utf8 ? (Utf8)this.startTime : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.endTime = null;
          } else {
            this.endTime = in.readString(this.endTime instanceof Utf8 ? (Utf8)this.endTime : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.errorMessage = null;
          } else {
            this.errorMessage = in.readString(this.errorMessage instanceof Utf8 ? (Utf8)this.errorMessage : null);
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.changedResourcesCount = null;
          } else {
            this.changedResourcesCount = in.readInt();
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.unchangedResourcesCount = null;
          } else {
            this.unchangedResourcesCount = in.readInt();
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.removedResourcesCount = null;
          } else {
            this.removedResourcesCount = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (phase == null ? 0 : ((java.lang.Enum) phase).ordinal());
    result = 31 * result + (runId == null ? 0 : runId.hashCode());
    result = 31 * result + (dataType == null ? 0 : ((java.lang.Enum) dataType).ordinal());
    result = 31 * result + (dataSourceId == null ? 0 : dataSourceId.hashCode());
    result = 31 * result + (dataSourceUrl == null ? 0 : dataSourceUrl.hashCode());
    result = 31 * result + (acceptHeader == null ? 0 : acceptHeader.hashCode());
    result = 31 * result + (fdkId == null ? 0 : fdkId.hashCode());
    result = 31 * result + (resourceUri == null ? 0 : resourceUri.hashCode());
    result = 31 * result + (startTime == null ? 0 : startTime.hashCode());
    result = 31 * result + (endTime == null ? 0 : endTime.hashCode());
    result = 31 * result + (errorMessage == null ? 0 : errorMessage.hashCode());
    result = 31 * result + (changedResourcesCount == null ? 0 : changedResourcesCount.hashCode());
    result = 31 * result + (unchangedResourcesCount == null ? 0 : unchangedResourcesCount.hashCode());
    result = 31 * result + (removedResourcesCount == null ? 0 : removedResourcesCount.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof HarvestEvent)) {
      return false;
    }
    HarvestEvent other = (HarvestEvent) o;
    if (!java.util.Objects.equals(this.phase, other.phase)) {
      return false;
    }
    if (Utf8.compareSequences(this.runId, other.runId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.dataType, other.dataType)) {
      return false;
    }
    if (Utf8.compareSequences(this.dataSourceId, other.dataSourceId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.dataSourceUrl, other.dataSourceUrl) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.acceptHeader, other.acceptHeader) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.fdkId, other.fdkId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.resourceUri, other.resourceUri) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.startTime, other.startTime) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.endTime, other.endTime) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.errorMessage, other.errorMessage) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.changedResourcesCount, other.changedResourcesCount)) {
      return false;
    }
    if (!java.util.Objects.equals(this.unchangedResourcesCount, other.unchangedResourcesCount)) {
      return false;
    }
    if (!java.util.Objects.equals(this.removedResourcesCount, other.removedResourcesCount)) {
      return false;
    }
    return true;
  }
}










