/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.fdk.rdf.parse;
@org.apache.avro.specific.AvroGenerated
public enum RdfParseResourceType implements org.apache.avro.generic.GenericEnumSymbol<RdfParseResourceType> {
  DATASET, DATA_SERVICE, CONCEPT, INFORMATION_MODEL, SERVICE, EVENT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RdfParseResourceType\",\"namespace\":\"no.fdk.rdf.parse\",\"symbols\":[\"DATASET\",\"DATA_SERVICE\",\"CONCEPT\",\"INFORMATION_MODEL\",\"SERVICE\",\"EVENT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
