/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.fdk.concept;
@org.apache.avro.specific.AvroGenerated
public enum ConceptEventType implements org.apache.avro.generic.GenericEnumSymbol<ConceptEventType> {
  CONCEPT_HARVESTED, CONCEPT_REASONED, CONCEPT_REMOVED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ConceptEventType\",\"namespace\":\"no.fdk.concept\",\"symbols\":[\"CONCEPT_HARVESTED\",\"CONCEPT_REASONED\",\"CONCEPT_REMOVED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
