/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.fdk.informationmodel;
@org.apache.avro.specific.AvroGenerated
public enum InformationModelEventType implements org.apache.avro.generic.GenericEnumSymbol<InformationModelEventType> {
  INFORMATION_MODEL_HARVESTED, INFORMATION_MODEL_REASONED, INFORMATION_MODEL_REMOVED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"InformationModelEventType\",\"namespace\":\"no.fdk.informationmodel\",\"symbols\":[\"INFORMATION_MODEL_HARVESTED\",\"INFORMATION_MODEL_REASONED\",\"INFORMATION_MODEL_REMOVED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
